# 科学计算库numpy

### 张浩然

### Windows10，64位操作系统
### 软件：Python 3.6 64-bit

In [1]:
import numpy as np

#### 一：numpy中使用array生成数组，该数组的类型

In [2]:
a = [1,2,3]
b = np.array([1,2,3])
print(a, type(a))
print(b, type(b))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [3]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c, type(c))
print(d, type(d))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] <class 'numpy.ndarray'>


#### 二：array生成的数组中数据的类型

In [4]:
print(b, b.dtype)
print(c, c.dtype)
print(d, d.dtype)

[1 2 3] int32
[[1 2 3]
 [4 5 6]] int32
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] int32


#### 三：指定数组中数据的类型；改变数组中数据的类型并赋给新变量

In [5]:
print(b.astype(np.string_))
print(c.astype(np.float64))#双精度浮点数
print(d.astype(np.int64))

[b'1' b'2' b'3']
[[1. 2. 3.]
 [4. 5. 6.]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
e = np.array([[1,2,3],[4,5,6]], dtype = np.float64)
print(e, e.dtype)

[[1. 2. 3.]
 [4. 5. 6.]] float64


In [7]:
f = np.array([1.2,2.3,3.4,4.5,5.6])
print(f, f.dtype)
print(f.astype(np.int32))

[1.2 2.3 3.4 4.5 5.6] float64
[1 2 3 4 5]


In [8]:
f.astype(np.int32)
print(f)

[1.2 2.3 3.4 4.5 5.6]


In [9]:
g = f.astype(np.int32)
print(g)

[1 2 3 4 5]


#### 四：查看数组的shape，改变数组的shape   每一个维度元素的个数

In [10]:
print(b, b.shape)
print(c, c.shape)
print(d, d.shape)

[1 2 3] (3,)
[[1 2 3]
 [4 5 6]] (2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)


In [11]:
print(b.reshape(1,3))
print(c.reshape(3,2))
print(d.reshape(3,2,2))

[[1 2 3]]
[[1 2]
 [3 4]
 [5 6]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [12]:
b.reshape(3,1)
print(b)

[1 2 3]


In [13]:
x = np.zeros((3,4))#生成全为0的矩阵
y = np.ones((3,4)) #生成全为1的矩阵
print(x, x.dtype)
print(y, y.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [14]:
z = np.full((3,4),8)#生成全为指定数字的矩阵
print(z, z.dtype)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]] int32


In [15]:
r = np.random.random((3,4))#生成0和1的随机数组
print(r)

[[0.32242487 0.00339117 0.37560448 0.21474549]
 [0.68793323 0.21766188 0.00762832 0.99558003]
 [0.15331976 0.06815463 0.28265136 0.90968524]]


In [16]:
r = np.random.rand(12).reshape(3,4) #生成0和1之间的随机数组 
t = np.random.randn(12).reshape(3,4)#生成-1和1之间的随机数组
print(r,"\n")
print(t,"\n")

[[0.23805459 0.24999534 0.94009252 0.95698102]
 [0.0981133  0.41358125 0.36286512 0.92107811]
 [0.79593222 0.86476777 0.18924042 0.11362709]] 

[[ 1.21567825 -0.19034155 -0.9108113  -0.73219198]
 [ 0.23351896 -1.84974178  1.77617044 -0.7409365 ]
 [ 1.22287539  0.90676245  0.43088526  0.7764839 ]] 



In [17]:
#u = np.random.rand((3,4))
u = np.random.rand(3,4)   #rand不能填元组
print(u)

[[0.32659869 0.74364904 0.85312853 0.41960645]
 [0.47932619 0.18245227 0.18322678 0.38113555]
 [0.83284898 0.56713715 0.43316508 0.43918435]]


#### 五：改变数组中的数据(引用和拷贝(view,copy))

In [18]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
arr_1 = arr[0][:2]
arr_2 = arr[0,:2]
print(arr_1)
print("")
print(arr_2)

[0 1]

[0 1]


In [20]:
arr[0,1] = 1111
print(arr)

[[   0 1111    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]


In [21]:
arr_0 = np.arange(12).reshape(3,4)
arr_9 = arr_0[:2,:2]
print(arr_9)

[[0 1]
 [4 5]]


In [22]:
print(arr_0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
arr_9[0,0] = 121212
print(arr_9)
print(arr_0)

[[121212      1]
 [     4      5]]
[[121212      1      2      3]
 [     4      5      6      7]
 [     8      9     10     11]]


In [24]:
arr = np.arange(12).reshape(3,4)
arr_0 = arr[:,:2].copy()#深拷贝
print(arr)
print(arr_0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]


In [25]:
arr_0[0,0] = 121212
print(arr)
print(arr_0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[121212      1]
 [     4      5]
 [     8      9]]


In [26]:
arr_1 = arr[:,:2].view()#浅拷贝
print(arr_1)
arr_1[0,0] = 121212
print("")
print(arr_1)
print("")
print(arr)

[[0 1]
 [4 5]
 [8 9]]

[[121212      1]
 [     4      5]
 [     8      9]]

[[121212      1      2      3]
 [     4      5      6      7]
 [     8      9     10     11]]


#### 六：选取数组中数据

In [27]:
six_arr = np.arange(12).reshape(3,4)
print(six_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
six_a = np.array([2,3,0])
print(six_arr[np.arange(3), six_a])

[2 7 8]


In [29]:
six_arr_0 = six_arr[np.arange(3), six_a].copy()
six_arr_0 += 10
print(six_arr_0, six_arr_0.shape)

[12 17 18] (3,)


#### 七：运算操作：加减乘除，开根号，矩阵乘法(dot，matmul)，matrix multiplication

In [30]:
s_a = np.array([[1,2],[3,4]])
s_b = np.array([[5,6],[7,8]])
print(s_a, s_a.shape)
print("")
print(s_b, s_b.shape)

[[1 2]
 [3 4]] (2, 2)

[[5 6]
 [7 8]] (2, 2)


In [31]:
print(s_a + s_b)  #加
print(np.add(s_a, s_b))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [32]:
print(s_a - s_b)  #减
print(np.subtract(s_a, s_b))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [33]:
print(s_a * s_b)  #乘
print(np.multiply(s_a, s_b))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [34]:
print(s_a / s_b)  #除
print(np.divide(s_a, s_b))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [35]:
print(np.sqrt(s_a))#开平方根
print(np.sqrt(s_b))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [36]:
#矩阵乘法
print(s_a)
print(s_b)
print("")
print(s_a.dot(s_b))
print(np.dot(s_a, s_b))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [37]:
print(np.matmul(s_a, s_b))#matrix multiplication

[[19 22]
 [43 50]]


In [38]:
s_c = np.arange(12).reshape(3,4)
s_d = np.arange(4)
print(np.dot(s_c, s_d))
print(np.matmul(s_c, s_d))

[14 38 62]
[14 38 62]


In [39]:
#在內积运算中，np.matmul与np.dot没有区别。
s_e = np.arange(24).reshape(2,3,4)
s_f = np.arange(12).reshape(4,3)
print(np.dot(s_e, s_f), np.dot(s_e, s_f).shape)
print(np.matmul(s_e, s_f), np.matmul(s_e, s_f).shape)

[[[ 42  48  54]
  [114 136 158]
  [186 224 262]]

 [[258 312 366]
  [330 400 470]
  [402 488 574]]] (2, 3, 3)
[[[ 42  48  54]
  [114 136 158]
  [186 224 262]]

 [[258 312 366]
  [330 400 470]
  [402 488 574]]] (2, 3, 3)


#### 八：转置：(.T和transpose)

In [40]:
e_arr = np.arange(4).reshape(2,2)
print(e_arr)
print(e_arr.T)
print(e_arr.transpose())

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]


In [41]:
e_arr_0 = np.arange(24).reshape(2,3,4)
print(e_arr_0)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [42]:
print(e_arr_0.T.shape)
print(e_arr_0.transpose(), e_arr_0.transpose().shape)

(4, 3, 2)
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]] (4, 3, 2)


In [43]:
print(e_arr_0.transpose(1,0,2), e_arr_0.transpose(1,0,2).shape)

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]] (3, 2, 4)


#### 九：求和，求平均数(axis = n，将第n维压扁)

In [44]:
#求和
n_arr = np.arange(12).reshape(3,4)
print(np.sum(n_arr))
print(np.sum(n_arr, axis = 0))
print(np.sum(n_arr, axis = 1))

66
[12 15 18 21]
[ 6 22 38]


In [45]:
#求平均数
print(np.mean(n_arr))
print(np.mean(n_arr, axis = 0))
print(np.mean(n_arr, axis = 1))

5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


#### 十：comulative sum & sumulative product

In [46]:
#comulative sum
t_arr = np.arange(12).reshape(3,4)
print(t_arr)
print("")
print(t_arr.cumsum())
print("")
print(t_arr.cumsum(axis = 0))
print("")
print(t_arr.cumsum(axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[ 0  1  3  6 10 15 21 28 36 45 55 66]

[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [47]:
#sumlative product
t_arr_0 = np.arange(1,13).reshape(3,4)      
print(t_arr_0)
print("")
print(t_arr_0.cumprod())
print("")
print(t_arr_0.cumprod(axis = 0))
print("")
print(t_arr_0.cumprod(axis = 1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[        1         2         6        24       120       720      5040
     40320    362880   3628800  39916800 479001600]

[[  1   2   3   4]
 [  5  12  21  32]
 [ 45 120 231 384]]

[[    1     2     6    24]
 [    5    30   210  1680]
 [    9    90   990 11880]]


#### 十一：broadcasting

In [48]:
ele_arr = np.arange(12).reshape(3,4)
print(ele_arr)
print("")
print(ele_arr * 2)
print(ele_arr * [2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [49]:
ele_a = np.arange(4)
print(ele_arr)
print(ele_a)
print("")
print(ele_arr * ele_a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]

[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]]


In [50]:
ele_b = np.arange(3).reshape(3,1)
print(ele_b)
print(ele_arr * ele_b)

[[0]
 [1]
 [2]]
[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]]


#### 十二：堆叠(concatenate);(vstack,hstack)(c_,r_)

In [51]:
arr_1 = np.arange(6).reshape(2,3)
arr_2 = np.arange(6,12).reshape(2,3)
print(arr_1)
print(arr_2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [52]:
#concatenate
print(np.concatenate([arr_1,arr_2], axis = 0))
print(np.concatenate([arr_1,arr_2], axis = 1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [53]:
#vstark,hstark
print(np.vstack((arr_1,arr_2)))#vertical    垂直
print(np.hstack((arr_1,arr_2)))#horizontal  水平

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [54]:
#c_;r_
print(np.r_[arr_1,arr_2])#按行堆叠
print(np.c_[arr_1,arr_2])#按列堆叠

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [55]:
print(np.c_[0:5,-5:0])

[[ 0 -5]
 [ 1 -4]
 [ 2 -3]
 [ 3 -2]
 [ 4 -1]]


#### 十三：拆分(split),拉伸(ravel)

In [56]:
arr = np.arange(12).reshape(3,4)
arr_f, arr_s, arr_t = np.split(arr,[1,2],axis = 1)
print(arr_f,"\n")
print(arr_s,"\n")
print(arr_t)

[[0]
 [4]
 [8]] 

[[1]
 [5]
 [9]] 

[[ 2  3]
 [ 6  7]
 [10 11]]


In [57]:
print(arr.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


#### 十五：逻辑运算：where(arr >  0,x,y）

In [58]:
arr_x = np.random.randn(20).reshape(4,5)
print(arr_x)

[[ 0.21914611  0.09521481 -1.92362148 -0.36414233 -0.54758309]
 [ 1.32589606  1.89144679  0.07337252 -1.02988998  0.80356259]
 [-0.26965833 -0.89153164  0.88082424  0.72199503 -2.02884646]
 [ 0.22669744 -0.26073233 -0.50530875 -0.91506122 -1.24806748]]


In [59]:
arr_y = arr_x > 0
print(arr_y)

[[ True  True False False False]
 [ True  True  True False  True]
 [False False  True  True False]
 [ True False False False False]]


In [60]:
arr_1 = np.arange(5)
arr_2 = np.arange(5,10)
print(np.where(arr_y,arr_1,arr_2))

[[0 1 7 8 9]
 [0 1 2 8 4]
 [5 6 2 3 9]
 [0 6 7 8 9]]


In [61]:
print(np.where(arr_x > 0, 1, 2))

[[1 1 2 2 2]
 [1 1 1 2 1]
 [2 2 1 1 2]
 [1 2 2 2 2]]


#### 十五：重复(repeat),(tile)

In [62]:
#repeat
arr = np.array([[1,2],[3,4]])
print(np.repeat(arr, 2))
print(np.repeat(arr, 2, axis = 0))
print(np.repeat(arr, 2, axis = 1))

[1 1 2 2 3 3 4 4]
[[1 2]
 [1 2]
 [3 4]
 [3 4]]
[[1 1 2 2]
 [3 3 4 4]]


In [63]:
print(np.repeat(arr, [1,2,3,4]))

[1 2 2 3 3 3 4 4 4 4]


In [64]:
#tile
print(np.tile(arr, 2))
print(np.tile(arr,(2,3)))

[[1 2 1 2]
 [3 4 3 4]]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]
